version: '2'
services:
  ftp-server:
    container_name: pure-ftp
    image: pure:0.0.1
    volumes:
      - /data/ftp:/srv/ftp
#      - /data/ftp:/var/log
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    restart: unless-stopped
